const partypack ={
    products:[
{"_id":"1",
    "name":"Fortnite",
    "image":"/images/p1.jpeg",
"price":150,
"guru":[1,2,3],
"description":"play fortnite",
"scheduleitems":["PVP","PVE","birthdaycheer"]},
{"_id":"2",
    "name":"Minecraft",
    "image":"/images/p1.jpeg",
"price":150,
"guru":[1,2],
"description":"play minecraft",
"scheduleitems":["PVP","MOD1","MOD2","birthdaycheer"]},
{"_id":"3",
    "name":"Dwarft Fortress",
    "image":"/images/p1.jpeg",
"price":150,
"guru":[1],
"description":"Play dorf fortress",
"scheduleitems":["PVP","PVE","birthdaycheer"]},
{"_id":"4",
    "name":"Quake 3",
    "image":"/images/p1.jpeg",
"price":150,
"guru":[2,4],
"description":"play quake 3",
"scheduleitems":["PVP","PVE","birthdaycheer"]},
    ]
}
export default partypack;