PUT http://localhost:5000/api/attendees/1 HTTP/1.1
content-type: application/json

        {
            "_id":"1",
            "attendees":[
                {"name":"simo kikkeli erkkilä",
                "email":"erkkilan.simo@gmail.com",
                "attends":true,
                "discord":"yes",
                "game":"yes"},
                {"name":"Dimpo Vimpo",
                "email":"jonne@web.com",
                "attends":false,
                "discord":"yes",
                "game":"yes"}
            ]
        }