PUT http://localhost:5001/api/attendees/2 HTTP/1.1
content-type: application/json

        {
            "attendees":[
                {"name":"Tarmo",
                "email":"Tarmo@gmail.com",
                "attends":false,
                "discord":"fuck YES",
                "game":"yes"},
                {"name":"Mahjong Man",
                "email":"xiao@xu.com"
                    }
            ]
        }