PUT http://localhost:5001/api/parties/605251a0e432d14abb0895bb HTTP/1.1
content-type: application/json

{
            "packageid":"2",
            "guruid":"4",
            "datetime":"2021-04-23T18:25:43.511Z",
            "duration":"2",
            "email":"wimppa@diudau.com",
            "phone":"+35840dsfdsffds3683295",
            "num_attendees":"922222",
            "schedule":["MOD1","MOD2","ppippeli"],
            "likes":["cats","tnt","adventure"],
            "description":"Tervetuloa mun partyyn!"
}